services:
  gateway_redis:
    image: redis:7.2.5
    restart: always
    container_name: "gateway_redis"
    hostname: "gateway_redis"
    ports:
      - "6490:6379"
    environment:
      - REDIS_PORT=6379
      - REDIS_DB=0
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=gateway_password
    command: ["redis-server", "--requirepass", "gateway_password", "--loglevel", "notice", "--maxmemory", "500mb"]
    volumes:
      - gateway_redis_data:/data
    networks:
      - backend-network

  user_redis:
    image: redis:7.2.5
    restart: always
    container_name: "user_redis"
    hostname: "user_redis"
    ports:
      - "6235:6379"
    environment:
      - REDIS_PORT=6379
      - REDIS_DB=0
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=user_password
    command: ["redis-server", "--requirepass", "user_password", "--loglevel", "notice", "--maxmemory", "500mb"]
    volumes:
      - user_redis_data:/data
    networks:
      - backend-network


  restaurant_redis:
    image: redis:7.2.5
    restart: always
    container_name: "restaurant_redis"
    hostname: "restaurant_redis"
    ports:
      - "6236:6379"
    environment:
      - REDIS_PORT=6379
      - REDIS_DB=0
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=restaurant_password
    command: [ "redis-server", "--requirepass", "restaurant_password", "--loglevel", "notice", "--maxmemory", "500mb" ]
    volumes:
      - restaurant_redis_data:/data
    networks:
      - backend-network

  location_redis:
    image: redis:7.2.5
    restart: always
    container_name: "location_redis"
    hostname: "location_redis"
    ports:
      - "6300:6379"
    environment:
      - REDIS_PORT=6379
      - REDIS_DB=0
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=location_password
    command: ["redis-server", "--requirepass", "location_password", "--loglevel", "notice", "--maxmemory", "500mb"]
    volumes:
      - location_redis_data:/data
    networks:
      - backend-network

  order_redis:
    image: redis:7.2.5
    restart: always
    container_name: "order_redis"
    hostname: "order_redis"
    ports:
      - "6301:6379"
    environment:
      - REDIS_PORT=6379
      - REDIS_DB=0
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=order_password
    command: ["redis-server", "--requirepass", "order_password", "--loglevel", "notice", "--maxmemory", "500mb"]
    volumes:
      - order_redis_data:/data
    networks:
      - backend-network

volumes:
  gateway_redis_data:
  user_redis_data:
  restaurant_redis_data:
  location_redis_data:
  order_redis_data:

networks:
  backend-network:
    external: true
