services:
  user_postgres:
    image: postgres:16.3
    container_name: "user_postgres"
    hostname: "user_postgres"
    environment:
      - POSTGRES_USER=user_user
      - POSTGRES_PASSWORD=user_password
      - POSTGRES_DB=user_database
    ports:
      - "5438:5432"
    volumes:
      - user_postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  restaurant_postgres:
    image: postgres:16.3
    container_name: "restaurant_postgres"
    hostname: "restaurant_postgres"
    environment:
      - POSTGRES_USER=restaurant_user
      - POSTGRES_PASSWORD=restaurant_password
      - POSTGRES_DB=restaurant_database
    ports:
      - "5440:5432"
    volumes:
      - restaurant_postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  location_postgres:
    image: postgres:16.3
    container_name: "location_postgres"
    hostname: "location_postgres"
    environment:
      - POSTGRES_USER=location_user
      - POSTGRES_PASSWORD=location_password
      - POSTGRES_DB=location_database
    ports:
      - "5439:5432"
    volumes:
      - location_postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

volumes:
  user_postgres_data:
  restaurant_postgres_data:
  location_postgres_data:

networks:
  backend-network:
    external: true
