services:
  order_mongo:
    image: mongo:latest
    container_name: order_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: order_user
      MONGO_INITDB_ROOT_PASSWORD: order_password
      MONGO_INITDB_DATABASE: order_database
    ports:
      - "7017:27017"
    volumes:
      - order_mongo_data:/data/db
    networks:
      - backend-network

  feedback_mongo:
    image: mongo:latest
    container_name: feedback_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: feedback_user
      MONGO_INITDB_ROOT_PASSWORD: feedback_password
      MONGO_INITDB_DATABASE: feedback_database
    ports:
      - "7018:27017"
    volumes:
      - feedback_mongo_data:/data/db
    networks:
      - backend-network

volumes:
  order_mongo_data:
  feedback_mongo_data:

networks:
  backend-network:
    external: true
